fix indentation

diff --git a/.github/workflows/dotnet-core.yml b/.github/workflows/dotnet-core.yml
--- a/.github/workflows/dotnet-core.yml
+++ b/.github/workflows/dotnet-core.yml
@@ -36,10 +36,10 @@ jobs:
       run: |
         dotnet test --configuration Release --results-directory artifacts --no-build --logger 'trx;LogFileName=test-results.trx'
     - uses: actions/upload-artifact@v2  # upload test results
-        if: success() || failure()        # run this step even if previous step failed
-        with:
-          name: test-results
-          path: *.trx
+      if: success() || failure()        # run this step even if previous step failed
+      with:
+        name: test-results
+        path: *.trx
     - name: Package
       if: github.event_name != 'pull_request'
       run: dotnet pack --configuration Release --no-build
